### ISSUE TITLE
使用demo无法跑起来，相关参数都已换成正式的， 报错Exception: No wechatpay platform certificate, please double check your init params.

### ISSUE THREAD

**Issue by huangbo-bo** [minibear2021/wechatpayv3#34]
Traceback (most recent call last):
  File ".\weixinpay.py", line 32, in <module>
    wxpay = WeChatPay(
  File "C:\Users\bob\AppData\Local\Programs\Python\Python38\lib\site-packages\wechatpayv3\__init__.py", line 38, in __init__
    self._core = Core(mchid=self._mchid,
  File "C:\Users\bob\AppData\Local\Programs\Python\Python38\lib\site-packages\wechatpayv3\core.py", line 26, in __init__
    self._init_certificates()
  File "C:\Users\bob\AppData\Local\Programs\Python\Python38\lib\site-packages\wechatpayv3\core.py", line 208, in _init_certificates
    raise Exception('No wechatpay platform certificate, please double check your init params.')
Exception: No wechatpay platform certificate, please double check your init params.

**Comment by minibear2021** [comment]
检查你的apiv3 key，无法确认的话请重置。

**Comment by minibear2021** [comment]
没有新的更新就关闭了。
